# Generated by Django 5.1.7 on 2025-03-27 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('reference', models.FloatField(default=0)),
                ('measured', models.FloatField(default=0)),
                ('error', models.CharField(blank=True, max_length=10)),
            ],
        ),
    ]
